development:
  adapter: postgresql
  encoding: unicode
  database: site
  pool: 5
  username: site_user
  password: siteuser
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: site_test
  pool: 5
  username: site_user
  password: siteuser
  host: localhost
  port: 5432